### PR TITLE
Updating to nmdc-json_2019_02_19.zip

### PR DESCRIPTION
**Pull request by jeffbaumes**
This data update includes EMSL data.

### CODE REVIEW

**Comment by kfagnan** [comment]
Nice!

Though the size of the datasets went down from 30TB to 6TB - is that an
issue with the units?

**Comment by jeffbaumes** [comment]
While I originally used a more raw TSV file from @dehays for data object information, in the last week he performed a data object filtering/curation to just include three specific files for each GOLD project. This is what @wdduncan now includes in the official JSON data drops. It was after that process that the total dataset size went down. I believe the units are correct, and I'm fairly sure the size total went up with the EMSL data inclusion, so those data sizes are represented as well.

**Comment by kfagnan** [comment]
Yes, sorry. I chatted with Emiley after sending this and she mentioned the
reduction in data that were included in the pilot.

**Comment by dehays** [comment]
@kfagnan I was curious about this - details here: https://docs.google.com/spreadsheets/d/1nFyzFsbFaVClApOyDVVAp4uXuzyufxdRM0LqFpHitpE/edit

As @jeffbaumes indicated - the first JAMO file set I produced had 12586 files because it included a large number of annotation files.  That sum of those file sizes was 35.4 Tb.

Retrieving only fastq, fna and faa produced a set of 3004 files with a total size of 5.3 Tb.  The EMSL files only add another 1.9 Tb.

Other things I looked into - why are there a total of 873 MetaG and MetaT, but 913 projects processed by JGI?  The answer is the 40 isolate genomes produced on the Wrighton study.  The inclusion of isolate genomes may also be part of the reason we see more fastq, fna, and faa files than the 873 each that would be expected.

**Comment by kfagnan** [comment]
Ah this makes sense, thank you!

We should figure out the NMDC stance on isolates. I believe these are meant
to be filtered out, though this gives me the ability to chat with
collaborators about it next week.

**Pull request merged**
